production:
  create.from.dde.server: true
  dde_server_ip: localhost:3001
  dde_server_username: admin
  dde_server_password: admin
  show_middle_name: true
  show_maiden_name: true
  show_birthyear: true
  show_birthmonth: true
  show_birthdate: true
  show_age: true
  show_region_of_origin: true
  show_district_of_origin: true
  show_t_a_of_origin: true
  show_home_village: true
  show_current_region: true
  show_current_district: true
  show_current_t_a: true
  show_current_village: true
  show_current_landmark: true
  show_cell_phone_number: true
  show_office_phone_number: true
  show_home_phone_number: true
  show_occupation: true
  user.management.url: http://localhost:3004

development:
  create.from.dde.server: true
  dde_server_ip: localhost:3001
  dde_server_username: admin
  dde_server_password: admin
  show_middle_name: true
  show_maiden_name: true
  show_birthyear: true
  show_birthmonth: true
  show_birthdate: true
  show_age: true
  show_region_of_origin: true
  show_district_of_origin: true
  show_t_a_of_origin: true
  show_home_village: true
  show_current_region: true
  show_current_district: true
  show_current_t_a: true
  show_current_village: true
  show_current_landmark: true
  show_cell_phone_number: true
  show_office_phone_number: true
  show_home_phone_number: true
  show_occupation: true
  user.management.url: http://localhost:3005

test: &TEST
  create.from.dde.server: false
  dde_server_ip: localhost:3001
  dde_server_username: admin
  dde_server_password: admin
  show_middle_name: false
  show_maiden_name: false
  show_birthyear: false
  show_birthmonth: false
  show_birthdate: false
  show_age: false
  show_region_of_origin: false
  show_district_of_origin: false
  show_t_a_of_origin: false
  show_home_village: false
  show_current_region: false
  show_current_district: false
  show_current_t_a: false
  show_current_village: false
  show_current_landmark: false
  show_cell_phone_number: false
  show_office_phone_number: false
  show_home_phone_number: false
  show_occupation: false
  user.management.url: http://localhost:3004
